spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: postgres
    jpa:
        properties:
            hibernate:
                default_schema: registar
        generate-ddl: on
        hibernate:
            ddl-auto: update

app:
    onlinesim:
        url: https://onlinesim.ru/api/
        apiKey: b60fda9e10f087dd9766561f5aa99610
