spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/registrar
        username: postgres
        password: postgres
    jpa:
        properties:
            hibernate:
                default_schema: registrar
        generate-ddl: on
        hibernate:
            ddl-auto: update
    jackson:
        default-property-inclusion: non_null

app:
    onlinesim:
        url: https://onlinesim.ru/api/
        apiKey: b60fda9e10f087dd9766561f5aa99610
